DESTINATION_FILE: /path/to/the/authorized_keys/file/in/.ssh/directory
AUTH_LOG: <path to the log file where linux keeps auth logs>

MASTER:
    URL: <url of master>
	ENDPOINT_LOG: /bipolar/log
    SECRET: <secret of the master>
